Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"

  config.vm.network "forwarded_port", guest: 4646, host: 4646

  config.vm.network "public_network", bridge: "wlp1s0" , ip: "192.168.1.30"

  config.vm.network "forwarded_port", guest: 4646, host: 4646, host_ip: "0.0.0.0"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
  
    vb.memory = "1024"
  end
   config.vm.provision "shell", inline: <<-SHELL

    yum install -y yum-utils
    yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    yum -y install nomad
    curl -fsSL https://get.docker.com/ | sh
    systemctl start docker && systemctl enable docker
   SHELL
end
