Vagrant.configure("2") do |config|
  config.vm.hostname = "fedora32"
  config.vm.box = "fedora/32-cloud-base"
  config.vm.provider :libvirt do |libvirt|
    libvirt.cpus = 1
    libvirt.memory = 1024
  end
end

